name: flutter_to_pdf
description: A package to export any Flutter widget to a PDF.
version: 0.0.1
homepage: https://github.com/dunef-com/flutter_to_pdf/tree/main
repository: https://github.com/dunef-com/flutter_to_pdf
issue_tracker: https://github.com/dunef-com/flutter_to_pdf/issues

environment:
  sdk: '>=3.0.0-196.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

